app/javascript/shared/components/ChatOption.vue
app/javascript/shared/components/ChatOptions.vue
app/javascript/widget/components/AgentMessageBubble.vue
app/javascript/widget/components/ChatFooter.vue
app/javascript/widget/components/QuickReplies.vue
app/javascript/widget/views/Messages.vue

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1xuhkH11Z4yEG8eNwyHUmTeNvweHgE53I%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=jEtCxcm)
<details><summary><b>Video</b></summary><br>
</details> 
In this PR we added the new Quick Replies component 🚀  In order to accomplish this, the following changes were required:
- Create new `QuickReplies.vue` component. Here is where all the options are rendered and it handles the state logic to keep the app state constant,
- Add this component to `Messages.vue`. This is one of the main views for the conversation screen.
- Update `ChatOption.vue` component so the options are displayed with the new design we agreed
- Make …

Feature | New Quick Replies component

---

app/controllers/api/v1/accounts/inboxes_controller.rb
app/controllers/api/v1/accounts/microsoft/authorizations_controller.rb
app/controllers/api/v2/accounts/reports_controller.rb
app/controllers/microsoft/callbacks_controller.rb
app/helpers/api/v2/accounts/reports_helper.rb
app/javascript/dashboard/api/reports.js
app/javascript/dashboard/modules/search/components/SearchHeader.vue
app/javascript/dashboard/modules/search/components/SearchTabs.vue
app/javascript/dashboard/modules/search/components/SearchView.vue
app/javascript/dashboard/routes/dashboard/settings/labels/AddLabel.vue
app/javascript/dashboard/routes/dashboard/settings/labels/EditLabel.vue
app/javascript/dashboard/routes/dashboard/settings/reports/LiveReports.vue
app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/MetricCard.vue
app/javascript/dashboard/store/modules/reports.js
app/models/contact_inbox.rb
app/views/api/v2/accounts/reports/conversation_traffic.erb
config/locales/en.yml
config/routes.rb
spec/controllers/api/v1/accounts/contacts/contact_inboxes_controller_spec.rb
spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
spec/controllers/api/v1/accounts/microsoft/authorization_controller_spec.rb
spec/controllers/api/v2/accounts/report_controller_spec.rb
yarn.lock

Please include a summary of the change and issue(s) fixed. Also, mention relevant motivation, context, and any dependencies that this change requires.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

Sync with Chatwoot 

---

.github/workflows/deploy_staging.yml

Add checkout to deploy staging workflow

add checkout to deploy staging

---

Gemfile.lock

Add `localhost` gem to `Gemfile.lock`

Fix | Add `localhost` gem to `Gemfile.lock`

---

app/javascript/widget/store/modules/conversation/actions.js

Feature || cause error on purpose to test sentry in staging

Feature || cause error on purpose to test sentry in staging

---

.github/actions/deployment/push-image-ecr/action.yml
.github/workflows/deploy_staging.yml
app/javascript/widget/store/modules/conversation/actions.js
docker-compose.yaml
docker/dockerfiles/webpack.Dockerfile

Previous env vars implementation are not working. 
We will try to set env vars from github secrets
- Create env file
- Get secrets from github
- Pass this variables to the action.yml to be set in the new env file
Testing will be in staging

Feature || Add env vars config from github secrets

---

.github/actions/deployment/push-image-ecr/action.yml

Fix whitespaces issue in action.yml

Fix whitespaces issue in action.yml 

---

.github/actions/deployment/push-image-ecr/action.yml

Deploy to staging failed... cache configuration is failing so this will be handle in future PRs, priority is with env vars

Feature || revertCacheChanges

---

.github/actions/deployment/push-image-ecr/action.yml
.github/workflows/deploy_staging.yml

Feature || Create env file and add env vars directly in github actions

Feature || Create env file and add env vars directly in github actions

---

.dockerignore
.github/actions/deployment/push-image-ecr/action.yml
.github/workflows/deploy_staging.yml
docker/Dockerfile

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18DBWf8Y5q39RtJMbXpqrtTZjXce7xDHwk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=2C3B-mM)
Please include a summary of the change and issue(s) fixed. Also, mention relevant motivation, context, and any dependencies that this change requires.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

Feature | try to add env files modifying dockerfile

---

.dockerignore
.github/actions/deployment/push-image-ecr/action.yml
.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml
config/webpacker.yml
docker/Dockerfile
docker/dockerfiles/webpack.Dockerfile
package.json
yarn.lock

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19QRy9MWzcdn4BWKLywGL2opRfcLmzxg%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=-poUra-)
Please include a summary of the change and issue(s) fixed. Also, mention relevant motivation, context, and any dependencies that this change requires.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

Fix/ revert to SSM Put parameters config

---

.github/actions/deployment/push-image-ecr/action.yml

Fix | add s to inputs

---

.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml

Required to avoid failures related to database connection on image build.
https://github.com/aplijobs/birdwoot/actions/runs/5079843415/jobs/9126075291

Adding CORS_WIDGET_CONFIG on deployment env vars

---

app/javascript/shared/components/CardButton.vue
app/javascript/shared/components/ChatCard.vue

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1tA22imEM0fBZABaoB3dDYaHrM1KpQxMk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=_DgvKTS)
<details><summary><b>Image</b></summary><br> 
</details>
The chat button component needed some style updates according to what we discuss in a slack thread https://apli.slack.com/archives/C04FF7QA6A3/p1685485422639619

Feature | Update Card Button component

---

app/controllers/widgets_controller.rb
app/models/concerns/content_attribute_validator.rb
docker/Dockerfile

- Adding image_url to message content_attributes validator to support quick replies with images on templates.
- Adding domain validation to dismiss check on develop
- Adding missing vips dependency for alpinelinux to fix that missing dependency for image processing.

Fixes related to image dependencies and quick replies

---

app/javascript/widget/components/QuickReplies.vue

Release 23.25.01

---

config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb

Revert (Feature | Introduce only_path for Attachment Model #103)

---

app/models/attachment.rb
app/models/concerns/avatarable.rb

Feature | Try to Fix `url_for` for Avatars

---

app/models/attachment.rb
app/models/concerns/avatarable.rb

Feature | Try to Fix url_for for Avatars #2

---

app/models/attachment.rb
app/models/concerns/avatarable.rb

Rever changes related to files debug.

Feature | Revert last debug changes

---

.github/workflows/deploy_staging.yml

Fix which Sidekiq docker image we are getting.

Feature | Fix `Sidekiq` Docker Image

---

config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb

Feature | Introduce `config.action_mailer.default_url_options`

---

config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb

Feature | Introduce `config.action_mailer.default_url_options` #2

---

config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb

Feature | Introduce `config.action_mailer.default_url_options` #3

---

.github/workflows/deploy_production.yml
app/javascript/shared/components/ChatOption.vue
app/javascript/widget/components/ConversationWrap.vue
app/javascript/widget/views/Messages.vue

RELEASE 2023-37-01

---

app/javascript/widget/components/AgentMessageBubble.vue

We where sending the quick reply title instead of the value

Hotfix | Change quick replies value sent

---

app/javascript/widget/store/modules/conversation/actions.js

Rollback last pr just to test if deploy works as expected without this change

Fix | Rollback last change

---

app/javascript/widget/components/ChatFooter.vue

Feature | Add logs in develop

---

app/javascript/widget/components/ChatFooter.vue
app/javascript/widget/views/Home.vue

Feature || Add logs

---

app/javascript/widget/components/ChatFooter.vue
app/javascript/widget/views/Home.vue

- https://github.com/aplijobs/birdwoot/pull/145

Release 25.09.02

---

app/builders/v2/report_builder.rb
app/models/contact.rb

This PR fixes some security vulnerabilities, as it is asked in [this card](https://app.clickup.com/t/86dxetnag).
- It adds \A at the beginning of a regex to ensure a validation applies to the full string and not just to an intermediate part.
- Replaced send with secure hash lookup: Instead of send(params[:metric]), we now use metric_methods[params[:metric]].call
- Created a metric_methods hash to map valid metric names to their corresponding method objects using method(:method_name).
- Simplified the validation: the metric:valid? method now just checks if the metric exists as a key in the hash. 

fix: fix security vulnerabilities

---

app/javascript/shared/components/ResizableTextArea.vue
app/javascript/widget/components/ChatAttachment.vue
app/javascript/widget/components/ChatInputWrap.vue
app/javascript/widget/store/modules/appConfig.js
app/javascript/widget/store/modules/specs/appConfig/getters.spec.js

Fix button and text area behaviour

fix: update send button and text msg input in chat widget
