app/javascript/dashboard/routes/auth/auth.routes.js

This change is required to set requireSignupEnabled: false so we can create and configure new accounts from UI.

Enable SignUp view to create multiple account from same installation

---

app/javascript/widget/components/FileBubble.vue

<details>
<summary>New File Bubble</summary>
</details>
-This PR aims just to add text-decoration: underline to the file uploaded 'Download button' in the chat. Also to change document icon to a solid one
- Run Chatwood [Locally](https://www.notion.so/apli/Chatwoot-local-configuration-bce491eb472a433ca3ec629b0d34844a)
- Upload a file

Feature || UI Enhancement -> Modify FileBubble text decoration

---

app/javascript/widget/assets/scss/_variables.scss
app/javascript/widget/components/ChatFooter.vue
app/javascript/widget/components/ChatHeader.vue
app/javascript/widget/components/ConversationWrap.vue
app/javascript/widget/components/layouts/ViewWithHeader.vue

<details>
<summary>New Chat viewx</summary>
</details>
<details>
<summary>Previous/ chatwood view less than 800px</summary>
</details>
-This PR aims just to center chat window view, all elements must be centered
- Run Chatwood [Locally](https://www.notion.so/apli/Chatwoot-local-configuration-bce491eb472a433ca3ec629b0d34844a)
- Verify new chat view is centered (header, conversation body, footer input msg)

Feature | UI Enhancement -> Center chat view over ipad and desktop

---

app/javascript/shared/components/ChatOption.vue
app/javascript/shared/components/ChatOptions.vue
app/javascript/widget/components/AgentMessageBubble.vue
app/javascript/widget/components/ChatFooter.vue
app/javascript/widget/components/QuickReplies.vue
app/javascript/widget/store/modules/conversation/getters.js
app/javascript/widget/store/modules/conversation/index.js
app/javascript/widget/store/modules/conversation/mutations.js
app/javascript/widget/views/Messages.vue

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1d98ZlYcTMLGAQ0G9Lvl6lf9Bp2dnS7IY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=yLFzzgD)
- Update the store object to handle the quick replies state
- Add getters for options and callback
- Add mutations for options and callback
There is nothing to test in this PR, since it doesn't affect anything. In the following PRs we will use this change to handle the interactive messages

Feature | Add Quick Replies to Vuex state

---

app/javascript/widget/components/ChatHeaderExpanded.vue
app/javascript/widget/components/TeamAvailability.vue

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1Lijy56WIPLBDyYk8PpwN6Ghnvb8f5uJ4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=hQ57Jch)
<details><summary><b>New behavior</b></summary><br>
</details> 
As a continuation from PR #7, the home screen required responsiveness fixes too, to match the behavior implemented in that PR

Feature | Responsiveness to `Start Conversation` screen

---

.github/actions/deployment/push-image-ecr/action.yml
.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml

We need Sentry release version to be the deploy commit hash, as this value is dynamic it must be updated by github actions, and in this way, it can be updated on the environment variables in was ecs. 
- Add SSM_VUE_APP_VERSION input in `action.yml` to hold the last commit hash
- Add this input reference in the `deploy-staging.yml `and `deploy-staging.yml` workflows
- Set this value only for Birdwoot. 
This should be tested in staging

Feature || add sentry release version with put parameter

---

.env.example
app/javascript/apm/index.js

Description
Add the configuration for support of elastic apm monitoring in Birdwoot.
How to test?
Unfortunately, connection to elastic apm can only be configured through the server, this means locally running versions cant connect. So we have to perform a deploy to staging in order to test that everything is working ok.

Feature || apm config

---

.github/actions/deployment/push-image-ecr/action.yml

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19YdU5EtdKAzjUXeTYxoLDsg1E8kNDdEdo%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=oZjhpX6)
Add `type` flag because the deployment workflow is crashing

Add type to AWS SSM put-parameter action

---

app/javascript/widget/store/modules/conversation/actions.js
docker-compose.yaml
docker/dockerfiles/webpack.Dockerfile

This PR removes prev environment variables configuration and also the harcoded `throw Error` as it was just for testing purposes

Feature || remove prev env vars config

---

app/javascript/packs/sdk.js
app/javascript/sdk/IFrameHelper.js
app/javascript/widget/store/modules/conversation/actions.js
app/javascript/widget/views/Home.vue

Bug introduced when partially refactoring "ref" var name to referral.
With this change it is now using "referral" across widget module.
Manual tests executed-

Fix ref references with referral full name

---

app/controllers/widgets_controller.rb
config/initializers/cors.rb

This is required to avoid allowing web plugin to be executed from insecure / unexpected destinations.
https://github.com/aplijobs/birdwoot/issues/50
Tested locally

Security | Adding CORS domain restriction based on webwidget url and widget filtering

---

app/javascript/widget/components/ChatHeader.vue
app/javascript/widget/components/TeamAvailability.vue
app/javascript/widget/i18n/locale/en.json
app/javascript/widget/i18n/locale/es.json
app/javascript/widget/mixins/availability.js

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1dcifD0z2NX9ZgZrO9TiJS2IY0G3c8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=CsP8y4R)
As a request from the product team, we are forcing to show the bot as online always. This change was done with the i18n resources already created in chatwoot, and we force to show the green dot indicator too.
Just run Birdwoot locally and the change must be applied immediatly

Feature | Force online status

---

app/models/attachment.rb
config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb

Trying to fix issue when uploading images on production.
Reference: https://stackoverflow.com/questions/7219732/rails-missing-host-to-link-to-please-provide-host-parameter-or-set-default-ur
Nope.

Feature | Introduce `only_path` for Attachment Model

---

app/javascript/shared/components/ChatOption.vue

<details><summary><b>Issue</b></summary><br>
https://github.com/aplijobs/birdwoot/assets/22230419/d8195a4c-42ac-4605-8844-fd6b1abcae37
</details> 
<details><summary><b>Fixed behavior</b></summary><br>
https://github.com/aplijobs/birdwoot/assets/22230419/61a6e284-9e60-40dc-ade6-0f95b2b9ee8a
</details> 
There was an edge case that causes an issue with the quick replies UX. What was happening is that the hover effect made affected the option border and font-weight, causing a change in the item size. Since the item grows a little bit, the wrap functionality of the flex container causes the last element in the row to be moved to the next row, making it impossible to click that option in particular.
Just needed to add some quick replies options to the local store and test their hover behavior 🚀

Enhancement | Change hover effect on Quick Replies

---

app/javascript/widget/components/ConversationWrap.vue
app/javascript/widget/views/Messages.vue

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1nFqBdax3FtrDm5X1xol422p5tAvQZA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=_VO-2fj)
<details><summary><b>Video</b></summary><br>
https://github.com/aplijobs/birdwoot/assets/22230419/084e08ff-1a39-4c27-bdd2-686925ff26b6
</details> 
As a request from the product team, we were asked to move the Quick Replies container to the scrollable container in the chat window.

Enhancement | Move Quick Replies to Scrollable container

---

app/javascript/widget/components/AgentMessageBubble.vue

<details><summary><b>Video</b></summary><br>
https://github.com/aplijobs/birdwoot/assets/22230419/428e9509-c682-4abf-880b-151968d50960
</details> 
We added the await statement so the quick replies container will disappear until the update message process is completed

Fix | Add await to dispatch action

---

app/javascript/widget/views/Home.vue

execute setCustomAttributes on widget home view load to enforce event trigger at backend.

Fix | enforce event trigger

---

app/javascript/widget/store/modules/conversation/actions.js

Undesired scenario:
- A send template message arrives with a set of quick replies for the user
- The user doesn't select any option
- A new message arrives without quick replies
- The previous quick replies options remain visible although there are from the previous message that is not valid anymore
<details><summary><b>Video</b></summary><br>
https://github.com/aplijobs/birdwoot/assets/22230419/bb80f39f-261f-4f37-b69e-61c22cbb937f
</details>

Enhancement | Clear unanswered quick replies when new message arrives

---

docker/Dockerfile

Apparently, there's been an issue with inconsistency between shared object libraries in the Alpine distribution and other dependencies required for this project. It's difficult to pinpoint the exact dependency that causes this, but previous Docker builds throw an error similar to this one:
```
...[omitted logs]
#7 24.98 Executing gdk-pixbuf-2.42.10-r6.trigger
#7 24.98 Error relocating /usr/lib/libgio-2.0.so.0: statx: symbol not found
#7 24.98 Error relocating /lib/libmount.so.1: statx: symbol not found
#7 24.98 ERROR: gdk-pixbuf-2.42.10-r6.trigger: script exited with error 127
...[omitted logs]
```
This seems to be a recurring issue with other repositories that use Alpine. Examples:
- https://github.com/gramineproject/gramine/issues/1836
- …

Removed Alpine repository for vips

---

app/javascript/widget/store/modules/conversation/actions.js

clear quick replies when new message arrives

---

app/javascript/widget/components/ChatFooter.vue
app/javascript/widget/views/Home.vue

We got this issue reported from product, in which exiting the conversation was keeping the same conversation and not starting a new one. So this PR aims to solve this [issue](https://apli.slack.com/archives/C056S4HAX50/p1739980017091299) 
We add the same behaviour that chatwoot has when starting a new conversation. 
Tested in local. 
Please test this in develop

Feature | Delete "cache" after exiting conversation
